/*
* Large-Scale Discovery, a network scanning solution for information gathering in large IT/OT network environments.
*
* Copyright (c) Siemens AG, 2016-2021.
*
* This work is licensed under the terms of the MIT license. For a copy, see the LICENSE file in the top-level
* directory or visit <https://opensource.org/licenses/MIT>.
*
 */

package database

var viewDefinitions = map[string]string{
	"hosts": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			id,
			address,
			ip,
			dns_name,
			other_names,
			hops,
			scan_cycle,

			ports_open,

			os_guess,
			os_smb,
			os_last_boot,
			os_uptime,
			os_admin_users,
			os_rdp_users,

			scan_started,
			scan_finished,
			scan_status,
			scan_ip,
			scan_hostname,

			input,
			input_size,

			timezone,
			lat,
			lng,
			postal_address,
			input_network,
			input_country,
			input_location,
			input_routing_domain,
			input_zone,
			input_purpose,
			input_company,
			input_department,
			input_manager,
			input_contact,
			input_comment,
			ad_name,
			ad_distinguished_name,
			ad_dns_name,
			ad_created,
			ad_last_logon,
			ad_last_password,
			ad_description,
			ad_location,
			ad_managed_by,
			ad_managed_by_gid,
			ad_managed_by_ou,
			ad_os,
			ad_os_service_pack,
			ad_os_version,
			ad_service_principal_name,
			ad_critical_object
		FROM 
			t_discovery_hosts;
	`,

	"services": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			id,
			address,
			ip,
			dns_name,
			other_names,
			scan_cycle,

			port,
			protocol,
			service,
			service_product,
			service_version,
			service_device_type,
			service_cpes,
			service_flavor,
			service_ttl,

			os_guess,
			os_smb,
			os_last_boot,
			os_uptime,
			os_admin_users,
			os_rdp_users,

			scan_started,
			scan_finished,
			scan_status,
			scan_ip,
			scan_hostname,

			input,
			input_size,

			timezone,
			lat,
			lng,
			postal_address,
			input_network,
			input_country,
			input_location,
			input_routing_domain,
			input_zone,
			input_purpose,
			input_company,
			input_department,
			input_manager,
			input_contact,
			input_comment,
			ad_name,
			ad_distinguished_name,
			ad_dns_name,
			ad_created,
			ad_last_logon,
			ad_last_password,
			ad_description,
			ad_location,
			ad_managed_by,
			ad_managed_by_gid,
			ad_managed_by_ou,
			ad_os,
			ad_os_service_pack,
			ad_os_version,
			ad_service_principal_name,
			ad_critical_object
		FROM 
			t_discovery_services;
	`,

	"scripts": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			id,
			address,
			ip,
			dns_name,
			other_names,
			scan_cycle,

			port,
			protocol,
			script_type,
			script_name,
			script_output,

			os_guess,
			os_smb,
			os_last_boot,
			os_uptime,
			os_admin_users,
			os_rdp_users,

			scan_started,
			scan_finished,
			scan_status,
			scan_ip,
			scan_hostname,

			input,
			input_size,

			timezone,
			lat,
			lng,
			postal_address,
			input_network,
			input_country,
			input_location,
			input_routing_domain,
			input_zone,
			input_purpose,
			input_company,
			input_department,
			input_manager,
			input_contact,
			input_comment,
			ad_name,
			ad_distinguished_name,
			ad_dns_name,
			ad_created,
			ad_last_logon,
			ad_last_password,
			ad_description,
			ad_location,
			ad_managed_by,
			ad_managed_by_gid,
			ad_managed_by_ou,
			ad_os,
			ad_os_service_pack,
			ad_os_version,
			ad_service_principal_name,
			ad_critical_object
		FROM 
			t_discovery_scripts;
	`,

	"banners": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_banners.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			trigger_plain,
			trigger_ssl,
			trigger_telnet,
			trigger_http,
			trigger_https,

			t_banners.scan_started,
			t_banners.scan_finished,
			t_banners.scan_status,
			t_banners.scan_ip,
			t_banners.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_banners
			LEFT JOIN t_discovery_services ON t_banners.id_t_discovery_service = t_discovery_services.id;
	`,

	"smb": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_smb_files.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			share,
			path,
			name,
			extension,
			mime,
			readable,
			writable,
			size_kb,
			last_modified,
			depth,
			properties,
			is_symlink,
			is_dfs,

			t_smb.folders_readable,
			t_smb.files_readable,
			t_smb.files_writable,

			t_smb.scan_started,
			t_smb.scan_finished,
			t_smb.scan_status,
			t_smb.scan_ip,
			t_smb.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_smb_files
			LEFT JOIN t_discovery_services ON t_smb_files.id_t_discovery_service = t_discovery_services.id
			LEFT JOIN t_smb ON t_smb_files.id_t_smb = t_smb.id;
	`,

	"nfs": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_nfs_files.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			share,
			path,
			name,
			extension,
			mime,
			readable,
			writable,
			flags,
			size_kb,
			last_modified,
			depth,
			properties,
			is_symlink,
			restrictions,

			t_nfs.folders_readable,
			t_nfs.files_readable,
			t_nfs.files_writable,

			t_nfs.scan_started,
			t_nfs.scan_finished,
			t_nfs.scan_status,
			t_nfs.scan_ip,
			t_nfs.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_nfs_files
			LEFT JOIN t_discovery_services ON t_nfs_files.id_t_discovery_service = t_discovery_services.id
			LEFT JOIN t_nfs ON t_nfs_files.id_t_nfs = t_nfs.id;
	`,

	"ssh": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_ssh.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			t_ssh.authentication_mechanisms,
			t_ssh.key_exchange_algos,
			t_ssh.server_key_algos,
			t_ssh.server_encrypt_algos,
			t_ssh.server_mac_algos,
			t_ssh.server_compress_algos,
			t_ssh.uses_guessed_key_exchange,
			t_ssh.protocol_version,

			t_ssh.scan_started,
			t_ssh.scan_finished,
			t_ssh.scan_status,
			t_ssh.scan_ip,
			t_ssh.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_ssh
			LEFT JOIN t_discovery_services ON t_ssh.id_t_discovery_service = t_discovery_services.id;
	`,

	"ssl_issues": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_ssl_issues.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			vhost,
			any_chain_invalid,
			any_chain_invalid_order,
			lowest_protocol,
			min_strength,
			insecure_renegotiation,
			accepts_client_renegotiation,
			insecure_client_renegotiation,
			session_resumption_with_id,
			session_resumption_with_tickets,
			no_perfect_forward_secrecy,
			compression,
			export_suite,
			draft_suite,
			sslv2_enabled,
			sslv3_enabled,
			rc4_enabled,
			md2_enabled,
			md5_enabled,
			sha1_enabled,
			early_data_supported,
			ccs_injection,
			beast,
			heartbleed,
			lucky_13,
			poodle,
			freak,
			logjam,
			sweet_32,
			drown,
			is_compliant_to_mozilla_config,

			t_ssl.scan_started,
			t_ssl.scan_finished,
			t_ssl.scan_status,
			t_ssl.scan_ip,
			t_ssl.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_cpes,
			t_discovery_services.service_flavor,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_ssl_issues
			LEFT JOIN t_discovery_services ON t_ssl_issues.id_t_discovery_service = t_discovery_services.id
			LEFT JOIN t_ssl ON t_ssl_issues.id_t_ssl = t_ssl.id;
	`,

	"ssl_ciphers": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_ssl_ciphers.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			vhost,
			protocol_version,
			cipher_id,
			iana_name,
			open_ssl_name,
			support_ecdh_key_exchange
			supported_elliptic_curves,
			rejected_elliptic_curves,
			key_exchange,
			key_exchange_bits,
			key_exchange_strength,
			key_exchange_info,
			forward_secrecy,
			authentication,
			encryption,
			encryption_mode,
			encryption_bits,
			encryption_strength,
			block_cipher,
			block_size,
			stream_cipher,
			mac,
			mac_bits,
			mac_strength,
			prf,
			prf_bits,
			prf_strength,
			export,
			draft,

			t_ssl.scan_started,
			t_ssl.scan_finished,
			t_ssl.scan_status,
			t_ssl.scan_ip,
			t_ssl.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_ssl_ciphers
			LEFT JOIN t_discovery_services ON t_ssl_ciphers.id_t_discovery_service = t_discovery_services.id
			LEFT JOIN t_ssl ON t_ssl_ciphers.id_t_ssl = t_ssl.id;
	`,

	"ssl_certificates": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_ssl_certificates.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			vhost,
			deployment_id,
			type,
			version,
			serial_number,
			valid_chain,
			chain_validated_by,
			subject,
			subject_cn,
			issuer,
			issuer_cn,
			alternative_names,
			valid_from,
			valid_to,
			public_key_algorithm,
			public_key_info,
			public_key_bits,
			public_key_strength,
			signature_algorithm,
			signature_hash_algorithm,
			crl_urls,
			ocsp_urls,
			key_usage,
			extended_key_usage,
			basic_constraints_valid,
			ca,
			max_path_length,
			sha1_fingerprint,

			t_ssl.scan_started,
			t_ssl.scan_finished,
			t_ssl.scan_status,
			t_ssl.scan_ip,
			t_ssl.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_ssl_certificates
			LEFT JOIN t_discovery_services ON t_ssl_certificates.id_t_discovery_service = t_discovery_services.id
			LEFT JOIN t_ssl ON t_ssl_certificates.id_t_ssl = t_ssl.id;
	`,

	"webcrawler": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_webcrawler_pages.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			t_webcrawler_vhosts.vhost,
			depth,
			url,
			redirect_url,
			redirect_count,
			t_webcrawler_pages.auth_method,
			t_webcrawler_pages.auth_success,
			response_code,
			response_message,
			response_content_type,
			response_headers,
			html_title,
			html_content,
			html_content_length,
			raw_links,
			t_webcrawler_vhosts.favicon_hash,

			t_webcrawler.scan_started,
			t_webcrawler.scan_finished,
			t_webcrawler.scan_status,
			t_webcrawler.scan_ip,
			t_webcrawler.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_webcrawler_pages
			LEFT JOIN t_discovery_services ON t_webcrawler_pages.id_t_discovery_service = t_discovery_services.id
			LEFT JOIN t_webcrawler ON t_webcrawler_pages.id_t_webcrawler = t_webcrawler.id
			LEFT JOIN t_webcrawler_vhosts ON t_webcrawler_pages.id_t_webcrawler_vhost = t_webcrawler_vhosts.id;
	`,

	"webenum": `
		CREATE OR REPLACE VIEW ? AS
		SELECT
			t_webenum_results.id,
			t_discovery_services.address,
			t_discovery_services.ip,
			t_discovery_services.dns_name,
			t_discovery_services.other_names,
			t_discovery_services.scan_cycle,
			t_discovery_services.port,
			t_discovery_services.protocol,

			name,
			vhost,
			url,
			redirect_url,
			redirect_count,
			redirect_out,
			auth_method,
			auth_success,
			response_code,
			response_message,
			response_content_type,
			response_headers,
			html_title,
			html_content,
			html_content_length,

			t_webenum.scan_started,
			t_webenum.scan_finished,
			t_webenum.scan_status,
			t_webenum.scan_ip,
			t_webenum.scan_hostname,

			t_discovery_services.service,
			t_discovery_services.service_product,
			t_discovery_services.service_version,
			t_discovery_services.service_device_type,
			t_discovery_services.service_ttl,
			t_discovery_services.os_guess,
			t_discovery_services.os_smb,
			t_discovery_services.os_last_boot,
			t_discovery_services.os_uptime,
			t_discovery_services.os_admin_users,
			t_discovery_services.os_rdp_users,

			t_discovery_services.input,
			t_discovery_services.input_size,

			t_discovery_services.timezone,
			t_discovery_services.lat,
			t_discovery_services.lng,
			t_discovery_services.postal_address,
			t_discovery_services.input_network,
			t_discovery_services.input_country,
			t_discovery_services.input_location,
			t_discovery_services.input_routing_domain,
			t_discovery_services.input_zone,
			t_discovery_services.input_purpose,
			t_discovery_services.input_company,
			t_discovery_services.input_department,
			t_discovery_services.input_manager,
			t_discovery_services.input_contact,
			t_discovery_services.input_comment,
			t_discovery_services.ad_name,
			t_discovery_services.ad_distinguished_name,
			t_discovery_services.ad_dns_name,
			t_discovery_services.ad_created,
			t_discovery_services.ad_last_logon,
			t_discovery_services.ad_last_password,
			t_discovery_services.ad_description,
			t_discovery_services.ad_location,
			t_discovery_services.ad_managed_by,
			t_discovery_services.ad_managed_by_gid,
			t_discovery_services.ad_managed_by_ou,
			t_discovery_services.ad_os,
			t_discovery_services.ad_os_service_pack,
			t_discovery_services.ad_os_version,
			t_discovery_services.ad_service_principal_name,
			t_discovery_services.ad_critical_object
		FROM t_webenum_results
			LEFT JOIN t_discovery_services ON t_webenum_results.id_t_discovery_service = t_discovery_services.id
			LEFT JOIN t_webenum ON t_webenum_results.id_t_webenum = t_webenum.id;
	`,
}
